name: vak-dev
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _tflow_select=2.1.0=gpu
  - absl-py=0.7.1=py36_0
  - astor=0.7.1=py_0
  - attrs=19.1.0=py_0
  - backcall=0.1.0=py_0
  - bleach=3.1.0=py_0
  - bokeh=1.2.0=py36_0
  - c-ares=1.15.0=h516909a_1001
  - ca-certificates=2019.6.16=hecc5488_0
  - certifi=2019.6.16=py36_1
  - click=7.0=py_0
  - cloudpickle=1.2.1=py_0
  - cycler=0.10.0=py_1
  - cytoolz=0.10.0=py36h516909a_0
  - dask=2.1.0=py_0
  - dask-core=2.1.0=py_0
  - dbus=1.13.6=he372182_0
  - decorator=4.4.0=py_0
  - defusedxml=0.5.0=py_1
  - distributed=2.1.0=py_0
  - entrypoints=0.3=py36_1000
  - expat=2.2.5=he1b5a44_1003
  - fontconfig=2.13.1=he4413a7_1000
  - freetype=2.10.0=he983fc9_0
  - gast=0.2.2=py_0
  - gettext=0.19.8.1=hc5be6a0_1002
  - glib=2.58.3=h6f030ca_1002
  - grpcio=1.16.1=py36hf8bcb03_1
  - gst-plugins-base=1.14.5=h0935bb2_0
  - gstreamer=1.14.5=h36ae1b5_0
  - h5py=2.9.0=nompi_py36hf008753_1102
  - hdf5=1.10.4=nompi_h3c11f04_1106
  - heapdict=1.0.0=py36_1000
  - icu=58.2=hf484d3e_1000
  - ipykernel=5.1.1=py36h5ca1d4c_0
  - ipython=7.6.1=py36h5ca1d4c_0
  - ipython_genutils=0.2.0=py_1
  - jedi=0.14.1=py36_0
  - jinja2=2.10.1=py_0
  - joblib=0.13.2=py_0
  - jpeg=9c=h14c3975_1001
  - json5=0.8.5=py_0
  - jsonschema=3.0.1=py36_0
  - jupyter_client=5.3.1=py_0
  - jupyter_core=4.4.0=py_0
  - jupyterlab=1.0.2=py36_0
  - jupyterlab_server=1.0.0=py_1
  - keras-applications=1.0.7=py_1
  - keras-preprocessing=1.0.9=py_1
  - kiwisolver=1.1.0=py36hc9558a2_0
  - libblas=3.8.0=10_openblas
  - libcblas=3.8.0=10_openblas
  - libffi=3.2.1=he1b5a44_1006
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libiconv=1.15=h516909a_1005
  - liblapack=3.8.0=10_openblas
  - libopenblas=0.3.6=h6e990d7_4
  - libpng=1.6.37=hed695b0_0
  - libprotobuf=3.9.0=h8b12597_0
  - libsodium=1.0.17=h516909a_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.0.10=h57b8799_1003
  - libuuid=2.32.1=h14c3975_1000
  - libxcb=1.13=h14c3975_1002
  - libxml2=2.9.9=h13577e0_1
  - locket=0.2.0=py_2
  - lz4-c=1.8.3=he1b5a44_1001
  - markdown=3.1.1=py_0
  - markupsafe=1.1.1=py36h14c3975_0
  - matplotlib=3.1.1=py36_0
  - matplotlib-base=3.1.1=py36hfd891ef_0
  - mistune=0.8.4=py36h14c3975_1000
  - mock=3.0.5=py36_0
  - msgpack-python=0.6.1=py36h6bb024c_0
  - nbconvert=5.5.0=py_0
  - nbformat=4.4.0=py_1
  - ncurses=6.1=hf484d3e_1002
  - notebook=6.0.0=py36_0
  - numpy=1.16.4=py36h95a1406_0
  - olefile=0.46=py_0
  - openblas=0.3.6=h6e990d7_4
  - openssl=1.1.1c=h516909a_0
  - packaging=19.0=py_0
  - pandas=0.24.2=py36hb3f55d8_0
  - pandoc=2.7.3=0
  - pandocfilters=1.4.2=py_1
  - parso=0.5.1=py_0
  - partd=1.0.0=py_0
  - pcre=8.41=hf484d3e_1003
  - pexpect=4.7.0=py36_0
  - pickleshare=0.7.5=py36_1000
  - pillow=6.0.0=py36he7afcd5_0
  - pip=19.1.1=py36_0
  - prometheus_client=0.7.1=py_0
  - prompt_toolkit=2.0.9=py_0
  - protobuf=3.9.0=py36he1b5a44_0
  - psutil=5.6.3=py36h516909a_0
  - pthread-stubs=0.4=h14c3975_1001
  - ptyprocess=0.6.0=py_1001
  - pygments=2.4.2=py_0
  - pyparsing=2.4.0=py_0
  - pyqt=5.9.2=py36hcca6a23_0
  - pyrsistent=0.15.3=py36h516909a_0
  - python=3.6.7=h357f687_1005
  - python-dateutil=2.8.0=py_0
  - pytz=2019.1=py_0
  - pyyaml=5.1.1=py36h516909a_0
  - pyzmq=18.0.2=py36hc4ba49a_1
  - qt=5.9.7=h52cfd70_2
  - readline=8.0=hf8c457e_0
  - scipy=1.3.0=py36h921218d_0
  - send2trash=1.5.0=py_0
  - setuptools=41.0.1=py36_0
  - sip=4.19.8=py36hf484d3e_1000
  - six=1.12.0=py36_1000
  - sortedcontainers=2.1.0=py_0
  - sqlite=3.29.0=hcee41ef_0
  - tblib=1.4.0=py_0
  - tensorboard=1.13.1=py36_0
  - tensorflow=1.13.1=py36_0
  - tensorflow-estimator=1.13.0=py_0
  - tensorflow-gpu=1.13.1=h0d30ee6_0
  - termcolor=1.1.0=py_2
  - terminado=0.8.2=py36_0
  - testpath=0.4.2=py_1001
  - tk=8.6.9=hed695b0_1002
  - toolz=0.10.0=py_0
  - tornado=6.0.3=py36h516909a_0
  - traitlets=4.3.2=py36_1000
  - wcwidth=0.1.7=py_1
  - webencodings=0.5.1=py_1
  - werkzeug=0.15.4=py_0
  - wheel=0.33.4=py36_0
  - xorg-libxau=1.0.9=h14c3975_0
  - xorg-libxdmcp=1.1.3=h516909a_0
  - xz=5.2.4=h14c3975_1001
  - yaml=0.1.7=h14c3975_1001
  - zeromq=4.3.2=he1b5a44_2
  - zict=1.0.0=py_0
  - zlib=1.2.11=h516909a_1005
  - zstd=1.4.0=h3b9ef0a_0
  - pip:
    - evfuncs==0.1.1
    - koumura==0.1.1a1
    - tqdm==4.32.2
prefix: /home/art/anaconda3/envs/vak-dev

